// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OHairGanic.DAL.Models;

public partial class Analysis
{
    public int Id { get; set; }

    public int CaptureId { get; set; }

    public double Oiliness { get; set; }

    public double Dryness { get; set; }

    public double DandruffScore { get; set; }

    public string Label { get; set; }

    public string ModelVersion { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Capture Capture { get; set; }
}