// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OHairGanic.DAL.Models;

public partial class Capture
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Angle { get; set; }

    public string ImageUrl { get; set; }

    public DateTime TakenAt { get; set; }

    public virtual ICollection<Analysis> Analyses { get; set; } = new List<Analysis>();

    public virtual User User { get; set; }
}