// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OHairGanic.DAL.Models;

public partial class Payment
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public float Amount { get; set; }

    public string Currency { get; set; }

    public string Provider { get; set; }

    public string QrPayload { get; set; }

    public string QrImagePath { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? PaidAt { get; set; }

    public virtual Order Order { get; set; }
}