// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OHairGanic.DAL.Models;

public partial class User
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string FullName { get; set; }

    public DateTime CreatedAt { get; set; }
    public string Status { get; set; } = "Active";
    public string PhoneNumber { get; set; }
    public string PasswordHash { get; set; }
    public string Role { get; set; } = "User";
    public virtual ICollection<Capture> Captures { get; set; } = new List<Capture>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}